const SUBJECTS = {
  DSA:{name:"Data Structure & Applications",code:"DI03032031",color:"#5b5ce2",units:[
    ["Unit I • Basic Concepts of Data Structures & OOP",6,["Data Structure Basic Concepts","Types of data structures","Time Complexity and Space Complexity","Asymptotic Notations and Big O","Best, Average and Worst case Time Complexity","OOPs Concepts","Class and Object","Constructors","Instance, Class and Static methods","Abstract Data Types","Recursive functions"]],
    ["Unit II • Stack and Queues",30,["Overview of Stack","Stack operations: Push and Pop","Stack implementation using List","Infix, Prefix and Postfix expressions","Postfix expression evaluation","Recursive functions: Factorial and Fibonacci","Overview of Queue","Queue operations: Enqueue and Dequeue","Queue implementation using List","Limitation of Single Queue","Circular Queue","Applications of Queue","Circular Queue vs Simple Queue"]],
    ["Unit III • Linked List",30,["Overview of Linked List","Types of Linked List","Singly linked list: insertion at beginning","Insertion at end","Insertion after a given node","Insertion before a given node","Deleting first and last node","Counting nodes","Circular Linked List","Circular vs Singly Linked List","Doubly Linked List","Applications of Linked List"]],
    ["Unit IV • Searching and Sorting",17,["Linear Search","Binary Search","Bubble Sort","Selection Sort","Quick Sort","Insertion Sort","Merge Sort"]],
    ["Unit V • Trees",17,["Binary Trees","Complete Binary Tree","Tree terms: level, degree, in-degree, out-degree, leaf node","Binary Search Tree insertion","Binary Search Tree deletion","Binary Search Tree searching","Inorder Traversal","Preorder Traversal","Postorder Traversal","Applications of Binary Tree"]]
  ]},
  JP:{name:"Java Programming",code:"DI03032021",color:"#e34d67",units:[
    ["Unit I • Introduction to Java Programming",20,["Java history and introduction","Features of Java and JVM architecture","Java applications and platform independence","JDK, JRE and JVM","Java environment setup and tools","Structure of a Java program","Compilation and execution process","Comments and documentation","Primitive data types and variables","Type conversion and casting","Arithmetic, relational, logical and bitwise operators","Operator precedence and associativity"]],
    ["Unit II • Object-Oriented Programming Concepts",20,["OOP fundamentals","Class, Object, Encapsulation, Inheritance, Polymorphism","Procedural vs Object-Oriented programming","Class definition and object creation","Memory allocation for objects","Object references and garbage collection","Access modifiers: public, private, protected, default","Data hiding and encapsulation","Getter and Setter methods","Methods and parameter passing","this keyword","Constructor types and chaining","Method overloading","Constructor overloading","Static variables, methods and blocks","final keyword"]],
    ["Unit III • Inheritance, Interfaces, and Packages",20,["Inheritance concepts and types","extends keyword","super keyword and constructor chaining","Single, multilevel and hierarchical inheritance","Method overriding","Dynamic method dispatch","Object class and methods","toString(), equals(), hashCode()","Interface definition and implementation","Multiple inheritance through interfaces","Default and static interface methods","Abstract classes and methods","Concrete methods in abstract classes","Abstract class vs Interface","Package creation and naming conventions","Import statement and package access","Built-in packages"]],
    ["Unit IV • Exception Handling and Multithreading",20,["Exception handling fundamentals","Exception hierarchy and types","try, catch, finally","Multiple catch blocks and exception propagation","throw and throws","Custom exception creation","Exception handling best practices","Multithreading concepts and benefits","Process vs Thread","Thread lifecycle and states","Thread creation approaches","Extending Thread class","Implementing Runnable interface"]],
    ["Unit V • Collections & File Handling",20,["String class and methods","String immutability","StringBuilder and StringBuffer","String operations and regular expressions","Collections Framework overview","List: ArrayList and LinkedList","Set: HashSet and TreeSet","Map: HashMap and TreeMap","Iterator and enhanced for-loop","File handling fundamentals","File class and operations","Byte streams vs Character streams","Reading and writing text files","Object serialization concepts","Serializable interface","ObjectInputStream and ObjectOutputStream"]]
  ]},
  CN:{name:"Computer Networking",code:"DI03000131",color:"#0891b2",units:[
    ["Unit I • Computer Network Fundamentals",17,["Need, advantages and applications of computer networks","Physical topologies: Star, Ring, Bus, Mesh, Tree, Hybrid","Internet standards: Protocol and Interface","Classification by transmission: Point-to-point, Broadcast","Classification by scale: PAN, LAN, WAN, MAN, VPN, Internet","Peer-to-Peer and Client-Server architecture","Advantages of Client-Server over Peer-to-Peer","OSI and TCP/IP models and comparison"]],
    ["Unit II • Devices, Media & Network Infrastructure",19,["Classification of Transmission Media","Role of different network devices","Repeaters","Hubs","Bridges","Switches: Layer 2 and Layer 3","Routers","Access Points","Firewalls: concept and principles","Network Management System: OS, CLI, administrative functions, interfaces","Ethernet, Fast Ethernet, Gigabit Ethernet","Wireless LAN","FDDI & CDDI","Software Defined Networking"]],
    ["Unit III • Physical, Data Link & Network Layers",24,["Twisted pair, Coaxial cable and Fiber optic cable","Wireless Medium as Physical Layer","ISM Band","Cable Modem","Data Link sublayers and functions","Error Control and Flow Control","Packet Switching","IP Addressing","CIDR and NAT","ICMP, ARP, RARP, DHCP, BOOTP","IPv4 and IPv6 comparison"]],
    ["Unit IV • Transport & Application Layers",24,["Transport Layer","TCP and UDP","Connection-oriented vs connectionless protocols","Application Layer","DNS — Domain Name System","World Wide Web and web browser","HTML in Internet services","Email system functions and user agent","Email message format","SMTP and POP3","FTP","Remote Login","Voice and Video over IP"]],
    ["Unit V • Network Security",16,["Introduction to Network Security","Cryptography","Security zones, DMZ, Internet, Intranet and VLAN","Security implications and Tunnelling","IP Security: overview, architecture, configuration","Virtual Private Network","Email security standards and principles","SMTP, PEM, PGP, S/MIME and spam","ISO, IT Act, Copyright Act and Cyber Laws in India","IT Act 2000 provisions and latest amendments","Social issues, hacking and precautions"]]
  ]},
  PEC:{name:"Principle of Electronics Communication",code:"DI03000121",color:"#f59e0b",units:[
    ["Unit I • Basics of Communication System",12,["EM wave spectrum, frequency bands and applications","Analog and digital signals","Pulse, impulse, saw-tooth, sinusoidal and rectangular signals","Time-domain and frequency-domain representation","Analog communication system block diagram","Digital communication system block diagram","Modulation: definition and classification","Noise in communication system","Noise classification","Signal-to-noise ratio (S/N)","Noise figure"]],
    ["Unit II • Amplitude Modulation (AM)",25,["Need of modulation","Modulation techniques","Modulating signal and carrier signal","Modulation index","Mathematical representation of AM signal","AM in time and frequency domain","Frequency spectrum","DSB and SSB band spectrum","Applications of DSB and SSB","Power relations in AM wave","Bandwidth","Power saving in SSB","DSBSC generation using balanced modulator","AM demodulation using envelope detector/diode","Superheterodyne receiver block diagram and working","Receiver waveforms","Selectivity, sensitivity, image frequency rejection and fidelity"]],
    ["Unit III • Frequency Modulation (FM)",25,["FM mathematical representation","Bessel function use (no derivation)","FM time-domain and frequency-domain representation","Frequency deviation ratio","FM modulation index numericals","Narrow Band FM and Wide Band FM","Phase Modulation: definition, waveforms and applications","Pre-emphasis and De-emphasis","PLL FM modulator","FM demodulators: Ratio detector and PLL","FM receiver block diagram and working","FM receiver waveforms","Compare AM, FM and PM"]],
    ["Unit IV • Sampling Theory & Waveform Coding",18,["Sampling theorem: statement and proof","Nyquist rate and interval","Aliasing error","Under-sampling, over-sampling and critical sampling","Ideal, natural and flat-top sampling","PAM","PWM","PPM","Quantization concept","Classification of quantization","PCM transmitter and receiver"]],
    ["Unit V • Electromagnetic Wave & Antenna",20,["Properties of EM wave","Resonant and nonresonant antennas","Ideal antenna","Principle of transmitting and receiving antenna","Radiation pattern","Polarization","Bandwidth","Beam width","Antenna resistance","Directivity and power gain","Antenna gain","Dipole antenna and radiation pattern","Unidirectional, bidirectional and omnidirectional radiation patterns","Loop antenna","Folded dipole antenna","Yagi-Uda antenna","Smart antenna"]]
  ]},
  DLD:{name:"Digital Logic Design",code:"DI03000111",color:"#7c3aed",units:[
    ["Unit I • Number Systems and Codes",17,["Binary, Octal, Decimal and Hexadecimal number systems","Conversion between number systems","Binary addition","Binary subtraction","Binary multiplication","Binary division","1's complement","2's complement","Subtraction using 1's and 2's complement","Binary codes"]],
    ["Unit II • Boolean Algebra & Logic Gates",23,["AND, OR, NOT, NAND, NOR, EX-OR, EX-NOR gates","Gate symbols and operations","Truth tables","Basic Boolean algebra theorems and properties","AND-OR-Invert implementation","Universal gates: NAND and NOR","Algebraic simplification of Boolean expressions","Sum of Product (SOP)","K-map simplification up to 4 variables","Don't-care condition in K-map"]],
    ["Unit III • Combinational Logic Circuits",23,["Half Adder","Full Adder","Half Subtractor","Full Subtractor","Parallel adder using half/full adders up to 4-bit","Encoder 4:2 and 8:3","Decoder 2:4 and 3:8","Multiplexer 2:1, 4:1, 8:1","Demultiplexer 1:2, 1:4, 1:8","Binary-to-Gray converter up to 4 bits","Gray-to-Binary converter up to 4 bits"]],
    ["Unit IV • Sequential Logic Circuits",23,["SR Flip-Flop","D Flip-Flop","JK Flip-Flop","T Flip-Flop","Master-Slave JK","Triggering methods","Serial-in Serial-out shift register","Serial-in Parallel-out shift register","Parallel-in Serial-out shift register","Parallel-in Parallel-out shift register","Ring Counter","Johnson Counter","4-bit asynchronous/ripple counter","4-bit synchronous up/down counter","BCD/Decade counter"]],
    ["Unit V • Memories & Logic Families",14,["RAM overview","SRAM","DRAM","ROM overview","PROM","EPROM","EEPROM","Logic family overview","Fan-in","Fan-out","Noise margin","Propagation delay","Power dissipation","Figure of merit","TTL vs CMOS vs ECL","E-waste management of digital ICs/chips"]]
  ]}
};

const stateKey="gtuStudyOS_v1";
const courseStart="2026-09-26";
const deadline="2026-10-20";
let state = loadState();
let timer = {mode:"focus", seconds:1500, running:false, interval:null};
const MODES={focus:1500,short:300,long:900};

function defaultState(){
  const done={}; Object.keys(SUBJECTS).forEach(s=>done[s]={});
  return {done,sessions:[],notes:{},chapters:{},dailyGoal:4,apiKey:"",model:"gemini-3.8-flash",theme:"light",lastStudy:null,streak:0};
}
function loadState(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(stateKey)||"{}")}}catch{return defaultState()}}
function save(){localStorage.setItem(stateKey,JSON.stringify(state))}
function toast(t){const el=document.getElementById("toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function allTasks(){let a=[];for(const [sid,s] of Object.entries(SUBJECTS))s.units.forEach((u,ui)=>u[2].forEach((t,ti)=>a.push({sid,ui,ti,text:t,weight:u[1]})));return a}
function isDone(x){return !!state.done[x.sid]?.[`${x.ui}-${x.ti}`]}
function subjectStats(sid){const s=SUBJECTS[sid], total=s.units.length, done=s.units.reduce((n,_,ui)=>n+(state.chapters?.[sid]?.[`${ui}`]?1:0),0);return {total,done,pct:total?Math.round(done/total*100):0}}
function totalStats(){const xs=Object.keys(SUBJECTS).map(subjectStats),total=xs.reduce((n,x)=>n+x.total,0),done=xs.reduce((n,x)=>n+x.done,0);return {total,done,pct:total?Math.round(done/total*100):0}}
function daysLeft(){const d=Math.ceil((new Date(deadline+"T23:59:59")-new Date())/86400000);return Math.max(0,d)}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function todaySessions(){return state.sessions.filter(x=>x.date===todayKey())}
function mark(sid,ui,ti,checked){state.done[sid] ||= {};state.done[sid][`${ui}-${ti}`]=checked;state.lastStudy=todayKey();save();renderAll()}
function switchView(v){if(v==="planner")v="dashboard";state.view=v;save();renderAll()}
function renderAll(){renderDashboard();renderSyllabus();renderTimer();renderAI();renderAnalytics();renderSettings();document.getElementById("pageTitle").textContent=({dashboard:"Dashboard",syllabus:"Syllabus Tracker",timer:"Focus Timer",ai:"AI",analytics:"Analytics",settings:"Settings"})[state.view]||"Dashboard";document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));}
function dateOnly(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function calendarDates(){const start=new Date(courseStart+"T00:00:00"),end=new Date(deadline+"T00:00:00");const out=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1))out.push(new Date(d));return out}
function renderCalendar(){const dates=calendarDates(), today=dateOnly(new Date()).getTime();return `<div class="calendar-strip">${dates.map(d=>{const t=dateOnly(d).getTime(),passed=t<today,active=t===today;return `<div class="calendar-day ${passed?"passed":""} ${active?"today":""}"><span>${d.toLocaleDateString(undefined,{weekday:"short"})}</span><b>${d.getDate()}</b>${passed?'<i>✓</i>':''}</div>`}).join("")}</div>`}
function renderDashboard(){
  const ts=totalStats(),dl=daysLeft(), chapters=ts.total, done=ts.done;
  const perDay=dl?Math.ceil((chapters-done)/dl):chapters-done;
  const pct=ts.pct;
  document.getElementById("view-dashboard").innerHTML=`
  <div class="card hero"><div class="eyebrow">GTU SEM 3 • ICT</div><h2>${pct===100?"Syllabus complete.":"Keep moving, one chapter at a time."}</h2><p>Your progress is saved automatically. Deadline: <b>20 October 2026</b>.</p><div class="progress progress-lg"><span style="width:${pct}%"></span></div><div class="progress-label"><b>${pct}%</b><span>${done} of ${chapters} chapters</span></div></div>
  <div class="grid g4" style="margin-top:16px"><div class="card kpi"><div class="label">OVERALL PROGRESS</div><div class="value">${pct}%</div><small>${done} of ${chapters} chapters</small></div><div class="card kpi"><div class="label">TO DEADLINE</div><div class="value">${dl}</div><small>${dl===1?"day":"days"} remaining</small></div><div class="card kpi"><div class="label">FOCUS TODAY</div><div class="value">${todaySessions().reduce((n,x)=>n+x.minutes,0)}m</div><small>focused minutes</small></div><div class="card kpi"><div class="label">CHAPTERS LEFT</div><div class="value">${chapters-done}</div><small>remaining</small></div></div>
  <div class="section-head"><div><h2>Study calendar</h2><p>Past dates are crossed automatically. Today is highlighted.</p></div></div>
  <div class="card calendar-card">${renderCalendar()}<div class="calendar-deadline"><span>Today → 20 October</span><b>${dl} ${dl===1?"day":"days"} left</b></div></div>
  <div class="section-head"><div><h2>Five subjects</h2><p>Chapter progress updates live.</p></div><button class="btn primary" onclick="switchView('syllabus')">Open syllabus →</button></div>
  <div class="grid g3">${Object.keys(SUBJECTS).map(sid=>{const s=SUBJECTS[sid],st=subjectStats(sid);return `<div class="card subject-card"><div class="subject-head"><div><div class="subject-code">${s.code}</div><div class="subject-title">${sid} — ${s.name}</div></div><div class="badge">${st.pct}%</div></div><div class="pct">${st.done}/${st.total} chapters</div><div class="progress"><span style="width:${st.pct}%"></span></div></div>`}).join("")}</div>`;
}
function renderSyllabus(){
  const active=window.syllabusFilter||"ALL";let html=`<div class="filters">${["ALL",...Object.keys(SUBJECTS)].map(x=>`<button class="filter ${active===x?"active":""}" onclick="window.syllabusFilter='${x}';renderSyllabus()">${x}</button>`).join("")}</div>`;
  const ids=active==="ALL"?Object.keys(SUBJECTS):[active];
  ids.forEach(sid=>{const s=SUBJECTS[sid],st=subjectStats(sid);html+=`<div class="card" style="margin-bottom:16px"><div class="section-head" style="margin:0 0 14px"><div><h2>${sid} — ${s.name}</h2><p>${st.done}/${st.total} chapters completed • ${st.pct}%</p></div><div style="width:170px"><div class="progress"><span style="width:${st.pct}%"></span></div></div></div>`;
    s.units.forEach((u,ui)=>{const key=`${ui}`;const ck=!!state.chapters?.[sid]?.[key];html+=`<label class="chapter-row ${ck?"done":""}"><input type="checkbox" ${ck?"checked":""} onchange="markChapter('${sid}',${ui},this.checked)"><span><b>Chapter ${ui+1}</b><em>${u[0].replace(/^Unit [IVX]+ • /,"")}</em></span><strong>${ck?"✓":""}</strong></label>`});html+=`</div>`});
  document.getElementById("view-syllabus").innerHTML=html;
}
function renderTimer(){
  const sw=fmt(stopwatch.seconds);
  document.getElementById("view-timer").innerHTML=`<div class="timer-wrap"><div class="card timer-card"><div class="eyebrow">POMODORO</div><div class="timer-mode">${Object.keys(MODES).map(m=>`<button class="${timer.mode===m?"active":""}" onclick="setTimer('${m}')">${m}</button>`).join("")}</div><div class="clock">${fmt(timer.seconds)}</div><div class="timer-label">${timer.mode}</div><div class="btn-row" style="justify-content:center;margin-top:18px"><button class="btn primary" onclick="toggleTimer()">${timer.running?"Pause":"Start"}</button><button class="btn secondary" onclick="resetTimer()">Reset</button></div><p class="hint" style="margin-top:18px">25 minutes focus → 5 minutes rest. Use the longer break after several cycles.</p></div><div class="card timer-card stopwatch-card"><div class="eyebrow">STOPWATCH</div><div class="stopwatch">${sw}</div><div class="btn-row" style="justify-content:center"><button class="btn primary" onclick="toggleStopwatch()">${stopwatch.running?"Pause":"Start"}</button><button class="btn secondary" onclick="resetStopwatch()">Reset</button></div><p class="hint" style="margin-top:18px">Use this when you want to track a custom study session.</p><div class="section-head" style="margin-top:28px"><div><h2>Session history</h2><p>Completed focus sessions are stored locally.</p></div></div><div class="session-list">${state.sessions.length?state.sessions.slice().reverse().slice(0,30).map(x=>`<div class="session"><span>${x.label}<small> • ${x.date}</small></span><b>${x.minutes} min</b></div>`).join(""):'<div class="empty">No sessions yet.</div>'}</div></div></div>`;
}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function setTimer(mode){clearInterval(timer.interval);timer.running=false;timer.mode=mode;timer.seconds=MODES[mode];renderTimer()}
function resetTimer(){clearInterval(timer.interval);timer.running=false;timer.seconds=MODES[timer.mode];renderTimer()}
function toggleTimer(){
  if(timer.running){clearInterval(timer.interval);timer.running=false;renderTimer();return}
  timer.running=true;renderTimer();timer.interval=setInterval(()=>{timer.seconds--;if(timer.seconds<=0){clearInterval(timer.interval);timer.running=false;if(timer.mode==="focus"){state.sessions.push({date:todayKey(),minutes:25,label:"25-minute focus"});save();toast("Focus session complete. Take a 5-minute break.");}timer.seconds=MODES[timer.mode];renderAll();}else{const c=document.querySelector(".clock");if(c)c.textContent=fmt(timer.seconds)}},1000)
}
function toggleStopwatch(){if(stopwatch.running){clearInterval(stopwatch.interval);stopwatch.running=false;renderTimer();return}stopwatch.running=true;renderTimer();stopwatch.interval=setInterval(()=>{stopwatch.seconds++;const el=document.querySelector(".stopwatch");if(el)el.textContent=fmt(stopwatch.seconds)},1000)}
function resetStopwatch(){clearInterval(stopwatch.interval);stopwatch.running=false;stopwatch.seconds=0;renderTimer()}
function markChapter(sid,ui,checked){state.chapters=state.chapters||{};state.chapters[sid]=state.chapters[sid]||{};state.chapters[sid][`${ui}`]=checked;save();renderAll()}
function syncChapters(){state.chapters=state.chapters||{};Object.entries(SUBJECTS).forEach(([sid,s])=>{state.chapters[sid]=state.chapters[sid]||{};s.units.forEach((u,ui)=>{if(state.chapters[sid][`${ui}`]===undefined){const all=u[2].every((_,ti)=>!!state.done[sid]?.[`${ui}-${ti}`]);state.chapters[sid][`${ui}`]=all}})})}
function renderAI(){
  const key=state.apiKey;
  document.getElementById("view-ai").innerHTML=`<div class="grid g2"><div class="card chat"><div class="section-head" style="margin:0"><div><h2>AI</h2><p>Ask for explanations, quizzes, revision plans or practice questions from your GTU syllabus.</p></div></div><div class="quick"><button onclick="quickAI('Make me a 10-question quiz from the current GTU Sem 3 syllabus. Give answers after the questions.')">10-question quiz</button><button onclick="quickAI('Explain the most important concepts I should revise today, using simple language.')">What should I revise?</button><button onclick="quickAI('Give me an active-recall session for one chapter. Ask one question at a time.')">Active recall</button><button onclick="quickAI('Make a 7-day revision plan from my remaining syllabus.')">7-day plan</button></div><div id="messages" class="messages"><div class="msg ai">I’m ready. I know your five subjects and the syllabus tracker state. Add a Gemini API key in Settings to enable live AI responses.</div></div><div class="chatbox"><textarea id="aiInput" placeholder="Ask AI anything about your studies…"></textarea><button class="btn primary" onclick="askAI()">Send</button></div></div><div class="card"><div class="eyebrow">CONTEXT</div><h2 style="font-family:'Space Grotesk'">Your live study state</h2>${Object.keys(SUBJECTS).map(s=>{let x=subjectStats(s);return `<div class="stat-row"><span>${s}</span><b>${x.pct}%</b></div>`}).join("")}<div class="stat-row"><span>Deadline</span><b>20 Oct 2026</b></div><div class="stat-row"><span>Chapters left</span><b>${totalStats().total-totalStats().done}</b></div><p class="hint" style="margin-top:15px">The AI prompt includes syllabus names and your progress, so it can make more relevant study help. Your key is stored only in this browser.</p></div></div>`;
}
function quickAI(t){document.getElementById("aiInput").value=t;askAI()}
function addMsg(text,who){const box=document.getElementById("messages");box.insertAdjacentHTML("beforeend",`<div class="msg ${who}">${escapeHTML(text)}</div>`);box.scrollTop=box.scrollHeight}
function escapeHTML(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function askAI(){
  const input=document.getElementById("aiInput"), q=input.value.trim();if(!q)return;input.value="";addMsg(q,"user");
  if(!state.apiKey){addMsg("Live AI is not configured yet. Open Settings → AI API key. The tracker itself works fully without AI.", "ai");return}
  addMsg("Thinking…","ai");
  const prompt=`You are a supportive GTU Diploma ICT Semester 3 study coach. Do not invent syllabus items. Use the supplied syllabus context and live progress. Be concise, exam-focused, and use active recall, spaced repetition, interleaving and practice. Subjects: ${Object.entries(SUBJECTS).map(([id,s])=>id+": "+s.name).join("; ")}. Progress: ${Object.entries(SUBJECTS).map(([id])=>id+" "+subjectStats(id).pct+"%").join(", ")}. Deadline: 20 October 2026. User request: ${q}`;
  try{
    const res=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(state.model)+":generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":state.apiKey},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:900}})});
    const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||"API error");
    const text=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("")||"No response.";
    document.querySelector("#messages .msg.ai:last-child")?.remove();addMsg(text,"ai");
  }catch(e){document.querySelector("#messages .msg.ai:last-child")?.remove();addMsg("AI request failed: "+e.message+" — check your API key/model in Settings.","ai")}
}
function renderAnalytics(){
  const ts=totalStats(), sessions=state.sessions.reduce((n,x)=>n+x.minutes,0);
  document.getElementById("view-analytics").innerHTML=`<div class="grid g4"><div class="card kpi"><div class="label">OVERALL</div><div class="value">${ts.pct}%</div><small>${ts.done}/${ts.total} chapters</small></div><div class="card kpi"><div class="label">FOCUS MINUTES</div><div class="value">${sessions}</div><small>tracked sessions</small></div><div class="card kpi"><div class="label">TODAY</div><div class="value">${todaySessions().reduce((n,x)=>n+x.minutes,0)}</div><small>focus minutes</small></div><div class="card kpi"><div class="label">REMAINING</div><div class="value">${ts.total-ts.done}</div><small>chapters</small></div></div><div class="section-head"><div><h2>Subject breakdown</h2><p>Your current chapter completion state.</p></div></div><div class="card">${Object.keys(SUBJECTS).map(id=>{const x=subjectStats(id);return `<div class="stat-row"><span><b>${id}</b> — ${SUBJECTS[id].name}</span><b>${x.done}/${x.total} • ${x.pct}%</b></div><div class="progress" style="margin:5px 0 13px"><span style="width:${x.pct}%"></span></div>`}).join("")}</div>`;
}
function renderSettings(){
  document.getElementById("view-settings").innerHTML=`<div class="grid g2"><div class="card"><div class="eyebrow">AI CONNECTION</div><h2 style="font-family:'Space Grotesk'">Gemini API</h2><div class="setting"><label>API key</label><input id="apiKey" type="password" value="${state.apiKey}" placeholder="Paste your Gemini API key"></div><div class="setting"><label>Model</label><input id="model" value="${state.model}"></div><p class="hint">Google currently documents Gemini API free access for eligible models/limits. This browser-only build sends the key directly to Google's API; do not use this setup for a public multi-user production site. See the official Gemini API docs for current limits.</p><button class="btn primary" onclick="saveAI()">Save AI settings</button></div><div class="card"><div class="eyebrow">LOCAL DATA</div><h2 style="font-family:'Space Grotesk'">Backup & reset</h2><p class="hint">Your progress, notes and sessions are stored in localStorage on this browser. Export a JSON backup before changing devices or clearing browser data.</p><div class="btn-row"><button class="btn secondary" onclick="exportData()">Export backup</button><button class="btn danger" onclick="resetData()">Reset all progress</button></div></div></div><div class="card" style="margin-top:16px"><div class="eyebrow">TRACKER FEATURES</div><div class="grid g3"><div><b>Live progress</b><p class="hint">Every checked syllabus chapter updates dashboard percentages instantly.</p></div><div><b>Focus timer</b><p class="hint">25/5 Pomodoro-style cycle plus 5- and 15-minute break modes.</p></div><div><b>Smart deadline</b><p class="hint">Remaining workload is divided across the days until 20 October.</p></div></div></div>`;
}
function saveAI(){state.apiKey=document.getElementById("apiKey").value.trim();state.model=document.getElementById("model").value.trim()||"gemini-3.8-flash";save();toast("AI settings saved");renderAI()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="gtu-sem3-study-backup.json";a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm("Reset every checked chapter, session and note? This cannot be undone unless you have a backup.")){const key=state.apiKey,model=state.model;state=defaultState();state.apiKey=key;state.model=model;syncChapters();save();toast("Progress reset");renderAll()}}
document.getElementById("nav").addEventListener("click",e=>{const b=e.target.closest(".nav-item");if(b)switchView(b.dataset.view)});
document.getElementById("exportBtn").onclick=exportData;
document.getElementById("importBtn").onclick=()=>document.getElementById("importFile").click();
document.getElementById("importFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...defaultState(),...JSON.parse(r.result)};syncChapters();save();renderAll();toast("Backup imported")}catch{toast("Invalid backup file")}};r.readAsText(f)};
window.addEventListener("beforeunload",()=>clearInterval(timer.interval));
syncChapters();
renderAll();
